core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dashboard.urls"), name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path

from .views import (index,
                    ProjectListView,
                    user_task_list,
                    ProjectDetailView,
                    TaskDetailView,
                    task_edit_view,
                    task_create_view,
                    TaskListView,
                    project_create_view,
                    project_edit_view,
                    TaskListArchiveView,
                    ProjectArchiveListView, )


urlpatterns = [
    path("", index, name="index"),
    path("projects/",
         ProjectListView.as_view(),
         name="projects"),
    path("projects/archive/",
         ProjectArchiveListView.as_view(),
         name="projects-archive"),
    path("projects/<int:pk>/",
         ProjectDetailView.as_view(),
         name="project-detail"),
    path("projects/create/",
         project_create_view,
         name="project-create"),
    path("projects/<int:pk>/edit/",
         project_edit_view,
         name="project-edit"),
    path("tasks/list/",
         TaskListView.as_view(),
         name="task-list"),
    path("tasks/list/archive/",
         TaskListArchiveView.as_view(),
         name="task-list-archive"),
    path("tasks/create/",
         task_create_view,
         name="task-create"),
    path("tasks/<int:pk>/",
         TaskDetailView.as_view(),
         name="task-detail"),
    path("tasks/<int:pk>/edit/",
         task_edit_view,
         name="task-edit"),
    path("my-tasks/<str:username>/", user_task_list, name="my-tasks")
    ]

app_name = "dashboard"

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination-center pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
 <div class="topnav">
  <div>
    <a href="{% url "dashboard:index" %}">Home page</a>
      {% if user.is_authenticated %}
        <a href="{% url "dashboard:my-tasks" username=user.username%}">My tasks</a>
      {% endif %}
    <a href="{% url "dashboard:task-list" %}">All tasks</a>
    <a href="{% url "dashboard:projects" %}">Projects</a>
    <a href="/admin/">Admin-panel</a>
  </div>
    {% if user.is_authenticated %}
      <div class="sidebar-user">
        <p>User: {{ user.username }}</p>
        <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Logout">
        </form>
      </div>
      {% else %}
        <div>
          <a href="{% url 'login' %}">Log in</a>
        </div>
      {% endif %}
 </div>