core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dashboard.urls"), name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path

from .views import (index,
                    ProjectListView,
                    user_task_list,
                    ProjectDetailView,
                    TaskDetailView,
                    task_edit_view,
                    task_create_view,
                    TaskListView,
                    project_create_view,
                    project_edit_view,
                    TaskListArchiveView,
                    ProjectArchiveListView, )


urlpatterns = [
    path("", index, name="index"),
    path("projects/",
         ProjectListView.as_view(),
         name="projects"),
    path("projects/archive/",
         ProjectArchiveListView.as_view(),
         name="projects-archive"),
    path("projects/<int:pk>/",
         ProjectDetailView.as_view(),
         name="project-detail"),
    path("projects/create/",
         project_create_view,
         name="project-create"),
    path("projects/<int:pk>/edit/",
         project_edit_view,
         name="project-edit"),
    path("tasks/list/",
         TaskListView.as_view(),
         name="task-list"),
    path("tasks/list/archive/",
         TaskListArchiveView.as_view(),
         name="task-list-archive"),
    path("tasks/create/",
         task_create_view,
         name="task-create"),
    path("tasks/<int:pk>/",
         TaskDetailView.as_view(),
         name="task-detail"),
    path("tasks/<int:pk>/edit/",
         task_edit_view,
         name="task-edit"),
    path("my-tasks/<str:username>/", user_task_list, name="my-tasks")
    ]

app_name = "dashboard"

dashboard/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from core import settings


class Position(models.Model):
    name = models.CharField(
        max_length=63,
    )

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(Position,
                                 on_delete=models.CASCADE,
                                 default=None,
                                 null=True,
                                 blank=True)

    class Meta:
        verbose_name = "employee"
        verbose_name_plural = "employees"
        ordering = ["last_name", "first_name"]

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}, " \
               f"position: {self.position}"

    def has_perm_project_edit(self) -> bool:
        if (self.position
                and self.position.name in ["Admin", "Project Manager"]):
            return True
        return False


class TaskType(models.Model):
    type = models.CharField(
        max_length=63,
    )

    def __str__(self):
        return self.type


class Project(models.Model):
    project_name = models.CharField(max_length=120, )
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    assignees = models.ManyToManyField(to=settings.AUTH_USER_MODEL,
                                       related_name="project")

    def __str__(self):
        return self.project_name


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("urgent", "Urgent"),
        ("critical", "Critical"),
    ]

    task_name = models.CharField(
        max_length=63,
    )
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=63, choices=PRIORITY_CHOICES, default="medium"
    )
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE, related_name="task")
    assignees = models.ManyToManyField(to=settings.AUTH_USER_MODEL, related_name="task")
    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                related_name="task",
                                default=None,
                                null=True,)

    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.task_name

    def task_status_repr(self) -> str:
        return "Completed" if self.is_completed else "Not Completed"

dashboard/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db.models import Q

from dashboard.models import Task, Project


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.DateInput(attrs={"type": "date"})
        }

    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        required=False)

    project = forms.ModelChoiceField(
        queryset=Project.objects.filter(is_completed=False),
        required=False
    )


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = "__all__"
        widgets = {
            "deadline": forms.DateInput(attrs={"type": "date"})
        }

    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        required=False)

    def clean_is_completed(self):
        is_completed = self.cleaned_data["is_completed"]
        project = self.cleaned_data.get("id")
        if is_completed and Task.objects.filter(Q(project=project) | Q(is_completed=False)):
            raise ValidationError("You cant complete this project, "
                                  "because you have not completed tasks")
        return is_completed

dashboard/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from dashboard.forms import TaskForm, ProjectForm
from dashboard.models import Task, Project


def index(request):
    num_tasks = Task.objects.count()
    last_added_task = Task.objects.latest("created_at") \
        if num_tasks else None
    context = {"num_tasks": num_tasks,
               "last_added_task": last_added_task}
    return render(request, "dashboard/index.html", context=context)


class ProjectListView(generic.ListView):
    model = Project
    queryset = Project.objects.filter(is_completed=False)
    paginate_by = 5
    ordering = ["-created_at"]


class ProjectArchiveListView(generic.ListView):
    model = Project
    queryset = Project.objects.filter(is_completed=True)
    paginate_by = 5
    ordering = ["-created_at"]
    template_name = "dashboard/project_list_archive.html"


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.filter(is_completed=False)
    paginate_by = 6
    ordering = ["-created_at"]


class TaskListArchiveView(generic.ListView):
    model = Task
    queryset = Task.objects.filter(is_completed=True)
    paginate_by = 6
    ordering = ["-created_at"]
    template_name = "dashboard/task_list_archive.html"


def task_edit_view(request: HttpRequest, pk: int) -> HttpResponse:
    current_task = get_object_or_404(Task, pk=pk)
    if request.method == "POST":
        form = TaskForm(request.POST, instance=current_task)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("dashboard:task-detail",
                                                kwargs={"pk": current_task.id}))
    else:
        form = TaskForm(instance=current_task)
    return render(request, "dashboard/task_update_form.html", context={"form": form,
                                                                       "current_task": current_task})


@transaction.atomic
def task_create_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        context = {
            "form": TaskForm()
        }
        return render(request, "dashboard/task_form.html", context=context)
    if request.method == "POST":
        form = TaskForm(request.POST)

        if form.is_valid():
            data = {
                "task_name": form.cleaned_data["task_name"],
                "description": form.cleaned_data["description"],
                "deadline": form.cleaned_data["deadline"],
                "is_completed": form.cleaned_data["is_completed"],
                "priority": form.cleaned_data["priority"],
                "task_type": form.cleaned_data["task_type"],
                "project": form.cleaned_data["project"]
            }
            task = Task.objects.create(**data)
            task.assignees.set(form.cleaned_data["assignees"])
            return HttpResponseRedirect(reverse("dashboard:task-detail",
                                                kwargs={"pk": task.id}))
        context = {
            "form": form
        }

        return render(request, "dashboard/task_form.html", context=context)


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()


@login_required
def user_task_list(request: HttpRequest, username: str) -> HttpResponse:
    current_user = get_user_model().objects.get(username=username)
    tasks = current_user.task.filter(is_completed=False)
    context = {"tasks": tasks}
    if request.method == "GET":
        return render(request,
                      "dashboard/user_task_list.html",
                      context=context)


@login_required
def project_edit_view(request: HttpRequest, pk: int) -> HttpResponse:
    current_project = get_object_or_404(Project, pk=pk)
    if request.method == "POST":
        form = ProjectForm(request.POST, instance=current_project)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("dashboard:project-detail",
                                                kwargs={"pk": current_project.id}))
    else:
        form = ProjectForm(instance=current_project)
    return render(request,
                  "dashboard/project_update_form.html",
                  context={"form": form,
                           "current_project": current_project})


@login_required
@transaction.atomic
def project_create_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        context = {
            "form": ProjectForm()
        }
        return render(request, "dashboard/project_form.html", context=context)
    if request.method == "POST":
        form = ProjectForm(request.POST)

        if form.is_valid():
            data = {
                "project_name": form.cleaned_data["project_name"],
                "description": form.cleaned_data["description"],
                "is_completed": form.cleaned_data["is_completed"],
            }

            project = Project.objects.create(**data)
            project.assignees.set(form.cleaned_data["assignees"])
            return HttpResponseRedirect(reverse("dashboard:project-detail",
                                                kwargs={"pk": project.id}))
        context = {
            "form": form
        }

        return render(request, "dashboard/project_form.html", context=context)

templates/dashboard/index.html
{% extends "base.html" %}

{% block content %}
  {% if user.is_authenticated %}
    <h1 class="index-h1">Welcome to SMART IT-Company Dashboard, {{ user.username }}!</h1>
    <hr>
    <h2 class="index-h2">Company current statistics:</h2>
    <div id="dashboard-content">
      <ul>
        <li>
          Total tasks created: {{ num_tasks }}
        </li>
        <li>
          Last added task:
          {% if last_added_task %}
          <a href="{% url "dashboard:task-detail" pk=last_added_task.id %}">{{ last_added_task.task_name }}</a>
          {% endif %}  
        </li>
      </ul>
    </div>
  {% else %}
    <h1>Welcome to SMART IT-Company Dashboard</h1>
    <hr>
    <div>
      <p>Please, log in to the system</p>
      <span><a href="{% url 'login' %}">Sign in</a></span>
    </div>
  {% endif %}
{% endblock %}

templates/dashboard/project_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h3 style="text-align: center; padding-top: 5px;">Detail info about project - {{ project.project_name }}</h3>
    {% if user.has_perm_project_edit %}
    <span><a class="edit-link" href="{% url "dashboard:project-edit" pk=project.id %}">Edit project</a>
    </span>
    {% endif %}
    <hr>
    <div class="project-info">
      <h4>Description:</h4>
      <p>{{ project.description }}</p>
      <hr>
      <h4>Assignees:</h4>
        {% for assigner in project.assignees.all%}
          <p class="assigner-project"> {{ assigner }} </p>
        {% endfor %}
      <hr>
    </div>
    <h5 style="text-align: center">Task list <a style="text-decoration: none;" href="{% url "dashboard:task-create" %}">(create task)</a></h5>
     <div class="task-list">
      {% for task in project.task.all %}
        <a href="{% url "dashboard:task-detail" pk=task.id %}">
          <div>
            <h6 style="text-align: center">{{ task.task_name }}</h6>
            <p>{{ task.deadline }}</p>
            <p>Status: {{ task.task_status_repr }}</p>
          </div>
        </a>
      {% endfor %}
     </div>
  </div>
{% endblock %}

templates/dashboard/project_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create new Project</h1>
  <form class="forms" action="{% url "dashboard:project-create" %}" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
   </form>
{% endblock %}

templates/dashboard/project_list.html
{% extends "base.html" %}
{% block content %}
  <div>
    <h4 class="task-list-head">Available project list
      <a class="btn btn-success" href="{% url "dashboard:project-create" %}">+ create new</a>
    </h4>
    <p class="archive-link"><a href="{% url "dashboard:projects-archive" %}">show completed projects</a>
    </p>
    <hr>
    <div class="project-list">
      {% for project in project_list %}
        <a href="{% url "dashboard:project-detail" pk=project.id %}">
          <div>
            <h4 style="text-align: center">
              {{ project.project_name }}
            </h4>
            <p>Description: {{ project.description }}</p>
            <span>Created: {{ project.created_at }}</span>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/dashboard/project_list_archive.html
{% extends "base.html" %}
{% block content %}
  <div>
    <h4 class="task-list-head">Closed project list
      <a class="btn btn-success" href="{% url "dashboard:project-create" %}">+ create new</a>
    </h4>
    <p class="archive-link"><a href="{% url "dashboard:projects" %}">show active projects</a>
    </p>
    <hr>
    <div class="project-list">
      {% for project in project_list %}
        <a href="{% url "dashboard:project-detail" pk=project.id %}">
          <div>
            <h4 style="text-align: center">
              {{ project.project_name }}
            </h4>
            <p>Description: {{ project.description }}</p>
            <span>Created: {{ project.created_at }}</span>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/dashboard/project_update_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Edit project {{ project.project_name }}</h1>
  <form class="forms" action="{% url "dashboard:project-edit" pk=current_project.id%}" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
   </form>
{% endblock %}

templates/dashboard/task_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h3 style="text-align: center; padding-top: 5px;">Detail info about task - {{ task.task_name }}:
    </h3>
    <a class="edit-link" href="{% url "dashboard:task-edit" pk=task.id%}">Edit current task</a>
    <hr>
    <div class="task-info">
      <h5 style="font-weight: bold">Description:</h5>
      <p class="task-descr">{{ task.description }}</p>
      <hr>
      <table>
        <tr>
          <th>Task type</th>
          <th>Deadline</th>
          <th>Project</th>
          <th>Status</th>
        </tr>
        <tr>
          <td>{{ task.task_type }}</td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.project }}</td>
          <td>{{ task.task_status_repr }}</td>
        </tr>
      </table>
      <hr>
      <div>
        <h5>Task employees:</h5>
        <ul>
          {% for employee in task.assignees.all %}
          <li>{{ employee }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create new task</h1>
  <form class="forms" action="{% url "dashboard:task-create" %}" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
   </form>
{% endblock %}

templates/dashboard/task_list.html
{% extends "base.html" %}

{% block content %}
<div>
  <h2 class="task-list-head">Active task list 
    <a class="btn btn-success" href="{% url "dashboard:task-create" %}">+ create new</a>
  </h2>
  <p class="archive-link"><a class="btn btn-link" href="{% url "dashboard:task-list-archive" %}">show completed tasks</a></p>
  <hr>
  <div class="task-list">
      {% for task in task_list %}
            <a href="{% url "dashboard:task-detail" pk=task.id %}">
              <div>
                <h5 style="text-align: center">{{ task.task_name }}</h5>
                <p>Deadline: {{ task.deadline }}</p>
                <span>Project: {{ task.project }}</span>
                <p>Created at: {{ task.created_at }}</p>
              </div>  
            </a>
      {% empty %}
      <p>There are no active tasks now</p>
      {% endfor %}
  </div>
</div>
{% endblock %}

templates/dashboard/task_list_archive.html
{% extends "base.html" %}

{% block content %}
<div>
  <h2 class="task-list-head">Completed task list 
    <a class="btn btn-success" href="{% url "dashboard:task-create" %}">+ create new</a>
  </h2>
  <p class="archive-link"><a class="btn btn-link" href="{% url "dashboard:task-list" %}">back to active tasks</a></p>
  <div class="task-list">
      {% for task in task_list %}
            <a href="{% url "dashboard:task-detail" pk=task.id %}">
              <div>
                <h5>{{ task.task_name }}</h5>
                <p>Deadline: {{ task.deadline }}</p>
                <span>Project: {{ task.project }}</span>
                <p>Created at: {{ task.created_at }}</p>
              </div>
            </a>
      {% empty %}
      <p>There are no active tasks now</p>
      {% endfor %}
  </div>
</div>
{% endblock %}

templates/dashboard/task_update_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Update task {{ task.task_name }}</h1>
  <form class="forms" action="{% url "dashboard:task-edit" pk=current_task.id%}" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
   </form>
{% endblock %}

templates/dashboard/user_task_list.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h2 class="task-list-head">My current tasks:</h2>
    {% if tasks %}
      <div id="dashboard-content">
        <ul>
          {% for task in tasks %}
            <li><a href="{% url "dashboard:task-detail" pk=task.id %}">{{ task.task_name }}</a>
              <p>Deadline: {{ task.deadline }}</p>
            </li>
          {% endfor %}
        </ul>
      </div>
    {% else %}
     <div class="info-userlist">
        <p>You don`t have active tasks now, but u can choose it from 
          <a href="{% url "dashboard:task-list" %}">Task list</a></p>
        <p>Or contact your Team-lead to take new tasks</p>
     </div>  
    {% endif %}
  </div>
{% endblock %}